name: nessai-ci
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy>=0.16
  - matplotlib>=2.0
  - seaborn
  - tqdm
  - pytorch>=1.11.0
  - cpuonly
  - glasflow
  - h5py
  - tqdm
  - corner
  - bilby
  - astropy
  - pytest
  - pytest-cov
  - pytest-timeout
  - pytest-rerunfailures
  - pytest-integration
  - pip
  - pip:
    - nflows
    - faiss-cpu>=1.7.3,!=1.7.4    # conda release for 1.7.4 is broken
    - ray[default] ; (sys_platform != 'win32' and python_version < '3.12') or (sys_platform == 'win32' and python_version < '3.12')
