name: nessai-ci
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy>=0.16
  - matplotlib>=2.0
  - seaborn
  - tqdm
  - pytorch>=1.11.0
  - cpuonly
  - glasflow
  - h5py
  - tqdm
  - corner
  - bilby
  - lalsuite
  - astropy
  - pytest
  - pytest-cov
  - pytest-timeout
  - pytest-rerunfailures
  - pytest-integration
  - ray-default # [py<312]
  - pip
  - pip:
    - nflows
