name: Unit tests

on:
  push:
    branches: [ main, release* ]
  pull_request:
    branches: [ main, release* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: Unit tests - Python ${{ matrix.python-version }} (${{ matrix.os }})

    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Ubuntu, Windows]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure mamba environment with Python ${{ matrix.python-version}}
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.8-0'
        environment-file: environment.yaml
        create-args: >-
          python=${{ matrix.python-version }}
        cache-environment: true
        post-cleanup: 'all'
    - name: Install nessai
      run: |
        pip install . --no-deps
    - name: Check dependencies
      if: success() || failure()
      run: |
        python -m pip check
    - name: Set MPL backend on Windows
      if: runner.os == 'Windows'
      run: |
        echo "MPLBACKEND=agg" >> $env:GITHUB_ENV
    - name: Print environment variables
      run: |
        env
    - name: Test with pytest
      run: |
        python -m pytest --cov-report=xml --without-integration --without-slow-integration
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
